name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Golf Romeo Alpha --  Execute!
        run: chmod +x gradlew

      - name: Speak 'Friend' And Enter
        run: |
          ls -R
          file gradle/wrapper/gradle-wrapper.jar
          ./gradlew --version

      - name: Be Ye Disablin' Of Yon Shielde
        run: ./gradlew lint

      - name: The Password Is Password
        run: echo "$KEYSTORE_B64" | base64 --decode > keystore.jks
        env:
          KEYSTORE_B64: ${{ secrets.DEBUG_KEYSTORE_B64 }}

      - name: Whole New World
        run: >
          ./gradlew assembleDebug
          -Pandroid.injected.signing.store.file=keystore.jks
          -Pandroid.injected.signing.store.password=${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
          -Pandroid.injected.signing.key.alias=${{ secrets.DEBUG_KEY_ALIAS }}
          -Pandroid.injected.signing.key.password=${{ secrets.DEBUG_KEY_PASSWORD }}

      - name: Get At Them Beans
        uses: actions/upload-artifact@v4
        with:
          name: ghost-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  unit_tests:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Ensure Lint Passes
        run: ./gradlew lint

      - name: Run Unit Tests
        run: ./gradlew test
